services:
  - type: web
    name: biblioteca-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: biblioteca-backend
          property: port
      # Las siguientes variables deben configurarse manualmente en Render Dashboard
      # - key: DB_HOST
      #   value: [tu-postgresql-host]
      # - key: DB_PORT
      #   value: 5432
      # - key: DB_USERNAME
      #   value: [tu-postgresql-username]
      # - key: DB_PASSWORD
      #   value: [tu-postgresql-password]
      # - key: DB_NAME
      #   value: biblioteca
      # - key: MONGODB_URI
      #   value: [tu-mongodb-connection-string]
      # - key: JWT_SECRET
      #   value: [tu-jwt-secret]
      # - key: JWT_REFRESH_SECRET
      #   value: [tu-refresh-token-secret]
      # - key: CORS_ORIGIN
      #   value: https://tu-frontend-url.onrender.com
